name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: build/distributions/*.zip
          body: |
            🚀 **Plugin Release** – ${{ github.ref_name }}

            - Searchable NestJS module selector
            - Compatible with IntelliJ/WebStorm 2023.2+
            - Kotlin 1.9.10 / Gradle 8.2

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}